LWMS/LWMS/Controllers/merchantsSetController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LWMS.Models;
using System.IO;
using LWMS.ViewModels;

namespace LWMS.Controllers
{    
    public class merchantsSetController : Controller
    {
       
        private repast_developmentEntities db = new repast_developmentEntities();
       
        // GET: merchantsSet
        public ActionResult Index()
        {
      
            return View(getAllMerchant());
        }

        public merchantext getAllMerchant()
        {
            var mer = db.merchants.Find((long)Session["sesMerchantID"]);
            var merext = new merchantext
            {
                id = mer.id,
                name = mer.name,
                pic = mer.pic,
                notice = mer.notice,
                join_full_reduce1 = (mer.join_full_reduce == null) ? false : ((bool)mer.join_full_reduce ? true : false),
                join_discount1 = (mer.join_discount == null) ? false : ((bool)mer.join_discount ? true : false),
                join_buy_gift1 = (mer.join_buy_gift == null) ? false : ((bool)mer.join_buy_gift ? true : false),
            };
            return merext;

        }

        /// <summary>
        /// 提交方法
        /// </summary>
        /// <param name="tm">模型数据</param>
        /// <param name="file">上传的文件对象，此处的参数名称要与View中的上传标签名称相同</param>
        /// <returns></returns>     
       [HttpPost]
        [MultipleButton(Name = "action", Argument = "upload")]
        public ActionResult upload(merchantext ext, HttpPostedFileBase image)
        {
            var mer = db.merchants.Find((long)Session["sesMerchantID"]);
            var merext = new merchantext
            {
                id = mer.id,
                name = mer.name,
                pic = mer.pic,
                notice = mer.notice,
                join_full_reduce1 = (mer.join_full_reduce == null) ? false : ((bool)mer.join_full_reduce ? true : false),
                join_discount1 = (mer.join_discount == null) ? false : ((bool)mer.join_discount ? true : false),
                join_buy_gift1 = (mer.join_buy_gift == null) ? false : ((bool)mer.join_buy_gift ? true : false),
            };
            try
            {
                if (image != null && image.ContentLength > 0)
                {
                    string fileName = DateTime.Now.ToString("yyyyMMdd") + "-" + Path.GetFileName(image.FileName);
                    string filePath = Path.Combine(Server.MapPath("~/Upload"), fileName);
                    image.SaveAs(filePath);
                    mer.pic = "~/Upload/" + fileName;
                    db.SaveChanges();
                    merext.pic = mer.pic;
                   
                }
                else
                {
                    return Content("没有文件！", "text/plain");
                }
                return RedirectToAction("Index", merext);
                
            }
            catch
            {
                return Content("上传异常 ！", "text/plain");
            }
            
            //var fileName = Path.Combine(Request.MapPath("~/Upload"), Path.GetFileName(file.FileName));
            //try
            //{
            //    File.SaveAs(fileName);
            //    //tm.AttachmentPath = fileName;//得到全部model信息
            //    tm.pic = "../upload/" + Path.GetFileName(File.FileName);
            //    //return Content("上传成功！", "text/plain");
            //    return RedirectToAction("Show", tm);
            //}
            //catch
            //{
            //    return Content("上传异常 ！", "text/plain");
            //}
        }
        [MultipleButton(Name = "action", Argument = "save")]
        public ActionResult save(merchantext ext, HttpPostedFileBase file_input)
        {
            var ses =Convert.ToInt64( Session["sesMerchantID"]) ;
            var mer = db.merchants.Find(ses );
                 
            try
            {
                if (file_input != null && file_input.ContentLength > 0)
                {
                    string fileName = DateTime.Now.ToString("yyyyMMddHHmmss") + "-" + Path.GetFileName(file_input.FileName);
                    string filePath = Path.Combine(Server.MapPath("~/Upload"), fileName);
                    file_input.SaveAs(filePath);
                    mer.pic = "~/Upload/" + fileName;
                  
                    mer.name = ext.name;
                   
                    mer.notice = ext.notice;
                    mer.join_full_reduce = (ext.join_full_reduce1);
                    mer.join_discount = (ext.join_discount1);
                    mer.join_buy_gift = (ext.join_buy_gift1);
                    db.SaveChanges();
                    return RedirectToAction("Index", getAllMerchant());

                }
                else
                {
                    return Content("没有文件！", "text/plain");
                }
            

            }
            catch
            {
                return Content("上传异常 ！", "text/plain");
            }
           
        }
        // GET: merchantsSet/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            merchants merchants = db.merchants.Find(id);
            if (merchants == null)
            {
                return HttpNotFound();
            }
            return View(merchants);
        }

        // GET: merchantsSet/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: merchantsSet/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,gourmet_palace_id,shop_id,boss,shopowner,name,enter_at,invest_status,pic,notice,qrcode,flavor,service,total_score,join_full_reduce,join_discount,join_buy_gift,created_at,updated_at,kitchen,order_count")] merchants merchants)
        {
            if (ModelState.IsValid)
            {
                db.merchants.Add(merchants);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(merchants);
        }

        // GET: merchantsSet/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            merchants merchants = db.merchants.Find(id);
            if (merchants == null)
            {
                return HttpNotFound();
            }
            return View(merchants);
        }

        // POST: merchantsSet/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,gourmet_palace_id,shop_id,boss,shopowner,name,enter_at,invest_status,pic,notice,qrcode,flavor,service,total_score,join_full_reduce,join_discount,join_buy_gift,created_at,updated_at,kitchen,order_count")] merchants merchants)
        {
            if (ModelState.IsValid)
            {
                db.Entry(merchants).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(merchants);
        }

        // GET: merchantsSet/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            merchants merchants = db.merchants.Find(id);
            if (merchants == null)
            {
                return HttpNotFound();
            }
            return View(merchants);
        }

        // POST: merchantsSet/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            merchants merchants = db.merchants.Find(id);
            db.merchants.Remove(merchants);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LWMS/LWMS/Views/merchantsSet/Create.cshtml
@model LWMS.Models.merchants

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>merchants</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.gourmet_palace_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.gourmet_palace_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.gourmet_palace_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.shop_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.shop_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.shop_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.boss, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.boss, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.boss, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.shopowner, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.shopowner, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.shopowner, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.enter_at, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.enter_at, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.enter_at, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.invest_status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.invest_status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.invest_status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.pic, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.pic, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.pic, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.notice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.notice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.notice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.qrcode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.qrcode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.qrcode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.flavor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.flavor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.flavor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.service, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.service, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.service, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.total_score, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.total_score, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.total_score, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.join_full_reduce, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.join_full_reduce)
                    @Html.ValidationMessageFor(model => model.join_full_reduce, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.join_discount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.join_discount)
                    @Html.ValidationMessageFor(model => model.join_discount, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.join_buy_gift, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.join_buy_gift)
                    @Html.ValidationMessageFor(model => model.join_buy_gift, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.created_at, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.created_at, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.created_at, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.updated_at, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.updated_at, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.updated_at, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.kitchen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.kitchen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.kitchen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.order_count, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.order_count, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.order_count, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

LWMS/LWMS/Views/merchantsSet/Delete.cshtml
@model LWMS.Models.merchants

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>merchants</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.gourmet_palace_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gourmet_palace_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.shop_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.shop_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.boss)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.boss)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.shopowner)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.shopowner)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.enter_at)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.enter_at)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.invest_status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.invest_status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.pic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.pic)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.notice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.notice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.qrcode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.qrcode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.flavor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.flavor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.service)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.service)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.total_score)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.total_score)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.join_full_reduce)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.join_full_reduce)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.join_discount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.join_discount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.join_buy_gift)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.join_buy_gift)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.created_at)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.created_at)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.updated_at)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.updated_at)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.kitchen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.kitchen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.order_count)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.order_count)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LWMS/LWMS/Views/merchantsSet/Details.cshtml
@model LWMS.Models.merchants

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>merchants</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.gourmet_palace_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gourmet_palace_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.shop_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.shop_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.boss)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.boss)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.shopowner)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.shopowner)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.enter_at)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.enter_at)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.invest_status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.invest_status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.pic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.pic)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.notice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.notice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.qrcode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.qrcode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.flavor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.flavor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.service)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.service)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.total_score)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.total_score)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.join_full_reduce)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.join_full_reduce)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.join_discount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.join_discount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.join_buy_gift)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.join_buy_gift)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.created_at)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.created_at)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.updated_at)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.updated_at)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.kitchen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.kitchen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.order_count)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.order_count)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

LWMS/LWMS/Views/merchantsSet/Index.cshtml
@model LWMS.ViewModels.merchantext

@{
    ViewBag.Title = "商户设置";
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>菜品管理</title>
    <script src="~/Scripts/jquery-1.10.2.js"></script>
</head>
<body>
    <script type="text/javascript">
        $(function () {
            $("#file_img").click(function () {
                $("#file_input").click(); //隐藏了input:file样式后，点击头像就可以本地上传
                $("#file_input").on("change", function () {
                    var objUrl = getObjectURL(this.files[0]); //获取图片的路径，该路径不是图片在本地的路径
                    if (objUrl) {
                        $("#file_img").attr("src", objUrl); //将图片路径存入src中，显示出图片
                    }
                });
            });
        });

        function getObjectURL(file) {
            var url = null;
            if (window.createObjectURL != undefined) { // basic
                url = window.createObjectURL(file);
            } else if (window.URL != undefined) { // mozilla(firefox)
                url = window.URL.createObjectURL(file);
            } else if (window.webkitURL != undefined) { // webkit or chrome
                url = window.webkitURL.createObjectURL(file);
            }
            return url;
        }

    </script>
    @using (Html.BeginForm("action", "merchantsSet", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <h4>商户设置</h4>
        <table style="border:1px solid #000;width:80%;">
            <tr style="background:#ebf1f1; ">
                <td colspan="2"><h5>基本信息设置</h5></td>
            </tr>
            <tr>
                <td>商户名称：</td>
                <td>@Html.TextBoxFor(model => model.name)</td>
            </tr>
            <tr style="height:100px;">
                <td>商户图片：</td>
                <td>
                    <div id="img_div_1">
                        <input type="file" accept="image/*" id="file_input" name="file_input" style="display:none" />
                        <div style="position: relative;">
                            @if (string.IsNullOrEmpty(Model.pic))
                            {

                                <img id="file_img" src="~/images/jiahao.jpg" name="pic" width="100" height="100" />
                            }
                  else
                       {
                                <img id="file_img" src="@Url.Content(Model.pic)" name="pic" width="100" height="100" />
                        }
                        </div>
                    </div>
                 @*<div>
        @if (string.IsNullOrEmpty(Model.pic))
        {

                            <img id="file_img" src= "~/images/jiahao.jpg" name="pic"  width="100" height="100" />
       }
        else
        {
            <img width="150" height="150" name="image" src="@Url.Content(Model.pic)" alt="images" />
        }
    </div>*@

                </td>
                <td>
                  
                    @*<div class="picture_an" id="UploadPhoto" style="width: 142px">
                        <input tabindex="3" title="支持jpg、jpeg、gif、png格式，文件小于5M" size="3" name="image" id="absFileInput" class="filePrew" type="file" />
                        <input type="submit" name="action:upload"  value="上传 "  class="btn btn-default" />
                        </div >*@

                </td>


            </tr>

        </table>

        <table style="border:1px;width:80%;">
            <tr>
                <td colspan="2">商户公告设置</td>
            </tr>
            <tr>
                <td>商户公告：</td>
                <td>@Html.TextAreaFor(model => model.notice)</td>
            </tr>

        </table>
        <table style="border:1px;width:80%;">
            <tr>
                <td colspan="2">营销活动参与设置</td>
            </tr>
            <tr>

                <td>@Html.CheckBoxFor(model => (model.join_full_reduce1), htmlAttributes: new { @class = "control-label col-md-2" }) 参与满减活动 </td>
                <td>@Html.CheckBoxFor(model => model.join_buy_gift1, htmlAttributes: new { @class = "control-label col-md-2" })参与买赠活动 </td>
                <td>@Html.CheckBoxFor(model => model.join_discount1, htmlAttributes: new { @class = "control-label col-md-2" })参与折扣活动 </td>

            </tr>

        </table>

        <p>
            <input type="submit" value="保存设置" name="action:save" class="btn btn-default" />

        </p>
    }
</body>
</html>