LWMS/LWMS/ViewModels/FoodcategoriesMerchant.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LWMS.ViewModels
{
    public class FoodcategoriesMerchant
    {
        public long id { get; set; }
        public string name { get; set; }
        public Nullable<int> sequence { get; set; }
       public string remark { get; set; }
        public string merchant_name { get; set; }
      // public Nullable<int> merchant_id { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    }
}

LWMS/LWMS/Controllers/FoodcategoriesMerchantController.cs
using LWMS.Models;
using LWMS.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace LWMS.Controllers
{
    public class FoodcategoriesMerchantController : Controller
    {
        private repast_developmentEntities db = new repast_developmentEntities();
        // GET: FoodcategoriesMerchant
        public IQueryable<FoodcategoriesMerchant> getFoodCat()
        {
            var sesid = (long)Session["sesMerchantID"];
            var mernameList = from mm in db.merchants
                          join fc in db.food_categories on mm.id equals (long)fc.merchant_id
                          where mm.id == sesid//??Session
                          select new FoodcategoriesMerchant
                          {
                              id = fc.id,
                              name = fc.name,
                              sequence = fc.sequence,
                              remark = fc.remark,
                              merchant_name = mm.name,
                              created_at = fc.created_at,
                              updated_at = fc.updated_at,
                          };
            return mernameList;
        }

        public ActionResult Index()
        {
           
//; IQueryable<FoodcategoriesMerchant> mernameList = from ff in db.food_categories
//                    select new FoodcategoriesMerchant
//                    {
//                        id = ff.id,
//                        name = ff.name,
//                        sequence = ff.sequence,
//                        remark = ff.remark,
//                        merchant_name =  db.merchants.Find(ff.id).name,
//                        // public Nullable<int> merchant_id { get; set; }
//                        created_at = ff.created_at,
//                        updated_at = ff.updated_at
//                    };

           // ViewData["merchantname"] = ;
            return View(getFoodCat() );          
        }

        // GET: food_categories/Create
        public ActionResult Create()
        {
            var sequenccount = db.food_categories.Count();
            sequenccount = (int)sequenccount * 10;
            
            //？？
            ViewData["sequenccount"] = sequenccount;
            return View("Create");
        }

        // POST: food_categories/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,sequence,remark,merchant_id,created_at,updated_at")] food_categories food_categories)
        {
            if (ModelState.IsValid)
            {
         
                //var age = Request["age"];
                //var btn = Request["button"];
                food_categories.created_at = DateTime.Now;
                food_categories.updated_at = DateTime.Now;
                //？？当前的登陆名称，商户
                food_categories.merchant_id = 1;
                db.food_categories.Add(food_categories);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(food_categories);
        }

        // GET: food_categories/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            food_categories food_categories = db.food_categories.Find(id);
           var mer =  (from m in db.merchants where m.id == (long)food_categories.merchant_id select m).First();
            ViewData["merchantname"] = mer.name;
            ViewData["created_at"] = mer.created_at;
            ViewData["updated_at"] = mer.updated_at;
            if (food_categories == null)
            {
                return HttpNotFound();
            }
            return View(food_categories);
        }

        // POST: food_categories/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,sequence,remark,merchant_id,created_at,updated_at")] food_categories food_categories)
        {
            if (ModelState.IsValid)
            {
                var sesid = (long)Session["sesMerchantID"];
                food_categories.merchant_id =(int) sesid;
                food_categories.updated_at = DateTime.Now;
                
                db.Entry(food_categories).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(food_categories);
        }

        // GET: food_categories/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            food_categories food_categories = db.food_categories.Find(id);
            if (food_categories == null)
            {
                return HttpNotFound();
            }
            return View(food_categories);
        }
        // POST: food_categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            food_categories food_categories = db.food_categories.Find(id);
            db.food_categories.Remove(food_categories);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LWMS/LWMS/Views/FoodcategoriesMerchant/Create.cshtml
@model LWMS.Models.food_categories


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>菜品分类管理</h4>
            <hr />
            <table class="table">
                <tr>
                    <td colspan="2">     @Html.ValidationSummary(true, "", new { @class = "text-danger" })         </td>
                </tr>
                <tr>
                    <td>名称：</td>
                    <td>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <span tyle="float:left;"> 排序号：</span>
                    </td>
                    <td>
                        <div class="col-md-10">
                            @Html.TextBox("sequence", ViewData["sequenccount"])
                            @Html.ValidationMessageFor(model => model.sequence, "", new { @class = "text-danger" })
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <span tyle="float:left;"> 备注：</span>
                    </td>
                    <td>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.remark, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.remark, "", new { @class = "text-danger" })
                        </div>
                    </td>
                </tr>
            </table>
          
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="保存" class="btn btn-default" />
                    <input type="button" onclick="javascript: history.go(-1);"  value="取消" name="action1" class="btn btn-default" />
                </div>
            </div>
              
        </div>
    }
    
    <div>
        @*@Html.ActionLink("Back to List", "Index")*@
    </div>
</body>
</html>

LWMS/LWMS/Views/FoodcategoriesMerchant/Delete.cshtml
@model LWMS.Models.food_categories



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>你确定要删除吗?</h3>
    <div>
        <h4>food_categories</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                名称	
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.name)
            </dd>
    
            <dt>
            排序号
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.sequence)
            </dd>
    
            <dt>
                备注
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.remark)
            </dd>
    
            <dt>
               创建人	
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.merchant_id)
            </dd>
    
            <dt>
              创建时间
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.created_at)
            </dd>
    
            <dt>
               修改时间
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.updated_at)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" />  
                <input type="button" onclick="javascript: history.go(-1);" value="取消" name="action1" class="btn btn-default" />
                @Html.ActionLink("Back to List", "Index")
                @*response.write"
                <script>alert('删除成功！');location.href='你想去的页面.asp?id="&动态id&"'</script>"*@
            </div>
        }
    </div>
</body>
</html>

LWMS/LWMS/Views/FoodcategoriesMerchant/Edit.cshtml
@model LWMS.Models.food_categories


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>菜品分类修改</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>菜品分类</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.id)
            <table class="table">
                <tr>
                    <td>
                        <span>名称</span>
                    </td>
                    <td>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        排序号
                    </td>
                    <td>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.sequence, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.sequence, "", new { @class = "text-danger" })
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        备注
                    </td>
                    <td>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.remark, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.remark, "", new { @class = "text-danger" })
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        创建人
                    </td>
                    <td>
                        <div class="col-md-10">
                     
                            <span>@ViewData["merchantname"].ToString()</span>
                            @Html.ValidationMessageFor(model => model.merchant_id, "", new { @class = "text-danger" })
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        创建时间
                    </td>
                    <td>
                        <div class="col-md-10">
                           
                            <span> @ViewData["created_at"].ToString()</span>
                            @Html.ValidationMessageFor(model => model.created_at, "", new { @class = "text-danger" })
                        </div>
                    </td>
                  
                </tr>
                <tr>
                    <td>  更新时间  </td>
                    <td>
                        <div class="col-md-10">
                           <span> @ViewData["updated_at"].ToString()</span>
                            @Html.ValidationMessageFor(model => model.updated_at, "", new { @class = "text-danger" })
                        </div>
                    </td>
                </tr>
            </table>
            
    
            @*<div class="form-group">
             创建时间	
                <div class="col-md-10">
                    @Html.LabelFor(model => model.created_at)
                    @Html.ValidationMessageFor(model => model.created_at, "", new { @class = "text-danger" })
                </div>
            </div>    
            <div class="form-group">
               更新时间
                <div class="col-md-10">
                    @Html.LabelFor(model => model.updated_at, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.updated_at, "", new { @class = "text-danger" })
                </div>
            </div>*@
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="保存" class="btn btn-default" />
                    @*@Html.ActionLink("取消", "Index")*@
                    <input type="button" onclick="javascript: history.go(-1);" value="取消" name="action1" class="btn btn-default" />
                    
                </div>
            </div>
        </div>
    }
    
    <div>
   
    </div>
</body>
</html>

LWMS/LWMS/Views/FoodcategoriesMerchant/Index.cshtml
@model IEnumerable<LWMS.ViewModels.FoodcategoriesMerchant> 


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>

<body>
    <style type="text/css">
        .tr1 {
            background-color: #FF9933;
        }
    </style>
    <script language="JavaScript">
        $(function () {
            //$("#tb tr")--选择id为tb的table，再选择该table的行tr
            // mouseover--鼠标放上去的事件（悬停）
            //$("#tb tr").mouseover();--给tb的行tr添加鼠标悬停事件
            $("#tb tr").not("#tr1").mouseover(function () {
                $(this).addClass("tr1");//添加样式tr1，$(this)表示当前选择的元素。
            });
            // mouseout--鼠标离开的事件
            $("#tb tr").mouseout(function () {
                $(this).removeClass("tr1");//去掉样式tr1
            });

            $("#tb tr").not("#tr1").click(function () {
                var content = $(this).children("td:eq(0)").text(); //添加样式tr1，$(this)表示当前选择的元素。
                if (content != "") {
                    alert(content);
                }
            });
        });
    </script>
    <div>
        <h4 style="background:#ebf1f1; ">菜品分类管理</h4>
        <hr />
        @using (Html.BeginForm("Create", "FoodcategoriesMerchant", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Get))
        {
            @Html.AntiForgeryToken()
            <h4>
                <input type="submit" value="添加菜品分类" name="action1" class="btn btn-default" />
            </h4>

        }
    </div>
    <table class="table" id="tb">
        <tr id="tr1">
            <th>
                编号
            </th>
            <th>
                名称
            </th>
            <th>
                排序号
            </th>
            <th>备注</th>

            <th>创建时间</th>

            <th> 创建人  </th>
            <th> 操作 </th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.id)
                </td>
                <td>
                    @item.name
                </td>
                <td>
                    @item.sequence

                </td>
                <td>
                    @item.remark
                </td>
                <td>   @item.created_at</td>
                <td>   @item.merchant_name</td>
                <td>
                    @Html.ActionLink("编辑", "Edit", new { id = item.id }) |

                @Html.ActionLink("删除", "Delete", new { id = item.id })
            </td>
        </tr>
        }
    </table>

</body>

</html>