LWMS/LWMS/Controllers/ShopperController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LWMS.Models;
using LWMS.ViewModels;

namespace LWMS.Controllers
{
    public class ShopperController : Controller
    {
        //password = System.Web.Security.FormsAuthentication.HashPasswordForStoringInConfigFile(password, "md5");
        private repast_developmentEntities db = new repast_developmentEntities();

        public void getList()
        {
            var data = from r in db.roles
                       where (r.role_type == 1)
                       select new
                       {
                           roleName = r.name,
                           roleid = r.id
                       };
             SelectList list = new SelectList(data, "roleid", "rolename");
           // ViewBag.StoreId = new SelectList(data, "roleid", "rolename");
            ViewBag.Roles = list;
            //ViewBag.StoreId = new SelectList(db.Stores, "StoreId", "Name", defaultStoreId);
        }

        // GET: Shopper
        public ActionResult Index()
        {
            getList();
            var ushop = from u in db.users
                        select new ShopperUser
                        {
                            id = u.id,
                            login_name = u.login_name,
                            name = u.name,
                            created_at = u.created_at,
                            created_user = u.created_user,
                        }; ;
            return View(ushop);
        }

        [HttpPost]
        [MultipleButton(Name = "action", Argument = "insert")]
        public ActionResult insert()
        {
            return View("Create");
        }

        [HttpPost]
        [MultipleButton(Name = "action", Argument = "setpassword")]
        public ActionResult setpassword(ShopperUser su)
        {
            //?? .Where(s=>s.merchant_id==1 )此商户的菜品种类
            if (su == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //设置密码123 不知道加密是怎么弄的
            users u = db.users.Find(su.id);
            if (u == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            u.encrypted_password = "123";
            db.SaveChanges();
            return View("Index");  
        }

        [HttpPost]
        [MultipleButton(Name = "action", Argument = "search")]
        public ActionResult search(ShopperUser su,string login_name,string name,string Roles)
        {
            //账号姓名角色
            users us = null;
            bool bexp = false;
            var u = from w in db.users
                          select w;
            if (!string.IsNullOrEmpty(login_name))
            {
                u = u.Where(w => w.login_name == login_name);
            }
            if (!string.IsNullOrEmpty(name))
            {
                u = u.Where(w => w.name == name);
            }
            if (!string.IsNullOrEmpty(Roles))
            {
                getList();
                var uid = (from w in db.role_users where (w.role_id==Convert.ToInt32(Roles))
                        select w.user_id);
                //List<int> list = new ArrayList<int>();
                //int[] a = new int[list.size()];
                //for (int i = 0; i < list.size(); i++)
                //{
                //    a[i] = list.get(i);
                //}

                List<int> uidint = new List<int>();
                if ((uid != null) && (uid.Count() > 0))
                {
                    foreach (int item in uid)
                    {                         
                       uidint.Add(item);                        
                    }
                    u = u.Where(w => (uidint.ToArray()).Contains( (int)w.id));
                }
                else
                {
                    return View("Index",null);
                }               
            }


            // us=  (from s in db.users where ((s.login_name == login_name) && (s.name == name)) select s).FirstOrDefault();
            //if ((su.login_name!=string.Empty))
            //    {
            //        us = (from s in db.users where ((s.login_name == su.login_name)) select s).FirstOrDefault();
            //    }
            //    else
            //    {
            //        us = (from s in db.users where ((s.name == su.name )) select s).FirstOrDefault();
            //    }
           
            var shop =  from use in u select 
            new ShopperUser{
                id = use.id,
                login_name = use.login_name,
                name = use.name,
                created_at = use.created_at,
                created_user = use.created_user,
               
            };
            getList();
            return View("Index",shop);
        }

        // GET: Shopper/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            users users = db.users.Find(id);
            if (users == null)
            {
                return HttpNotFound();
            }
            return View(users);
        }

        // GET: Shopper/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        // POST: Shopper/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,login_name,name,photo,created_user,created_at,updated_at,encrypted_password,remember_created_at,sign_in_count,current_sign_in_at,last_sign_in_at")] users users)
        {
            //得到当前的model 设置店长  角色中修改，商户中修改 
            if (ModelState.IsValid)
            {
                users us =( from u in db.users where ((u.login_name == users.login_name) &&(u.name==users.name)) select u).FirstOrDefault() ;
            role_users r = (from ru in db.role_users where (ru.user_id == us.id) select ru).FirstOrDefault();
            //找到userID 设置roleid，merchants的店长加上
            //  r.role_id = 0;
                db.users.Add(users);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(users);
        }

        // GET: Shopper/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            users users = db.users.Find(id);
            if (users == null)
            {
                return HttpNotFound();
            }
            return View(users);
        }

        // POST: Shopper/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,login_name,name,photo,created_user,created_at,updated_at,encrypted_password,remember_created_at,sign_in_count,current_sign_in_at,last_sign_in_at")] users users)
        {
            if (ModelState.IsValid)
            {
                db.Entry(users).State =System.Data.Entity. EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(users);
        }

        // GET: Shopper/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            users users = db.users.Find(id);
            if (users == null)
            {
                return HttpNotFound();
            }
            return View(users);
        }

        // POST: Shopper/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            users users = db.users.Find(id);
            db.users.Remove(users);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LWMS/LWMS/Views/Shopper/Create.cshtml
@model LWMS.Models.users

@{
    ViewBag.Title = "Create";
}

<h4>店长管理</h4>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>users</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <table class="table">
            <tr><td> 账号：
                </td>
                <td>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.login_name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.login_name, "", new { @class = "text-danger" })
                    </div>
                </td>
            </tr>

            <tr>
                <td>
                    姓名：
                </td>
                <td>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                    </div>
                </td>
            </tr>

            <tr>
                <td>
                    身份证号：
                </td>
                <td>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.real_name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.real_name, "", new { @class = "text-danger" })
                    </div>
                </td>
            </tr> 
        </table> 
 
 
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="保存" class="btn btn-default" />
                <input type="button" onclick="javascript: history.go(-1);" value="取消" name="cancel" class="btn btn-default" />
            </div>
        </div>
    </div>
}

LWMS/LWMS/Views/Shopper/Delete.cshtml
@model LWMS.Models.users

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>你确定要删除吗？</h3>
<div>
    <h4>users</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
           账号
        </dt>

        <dd>
            @Html.DisplayFor(model => model.login_name)
        </dd>

        <dt>
        用户名
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

       

        <dt>
          创建人
        </dt>

        <dd>
            @Html.DisplayFor(model => model.created_user)
        </dd>

        <dt>
          创建时间
        </dt>

        <dd>
            @Html.DisplayFor(model => model.created_at)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.updated_at)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.updated_at)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.encrypted_password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.encrypted_password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.remember_created_at)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.remember_created_at)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sign_in_count)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sign_in_count)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.current_sign_in_at)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.current_sign_in_at)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.last_sign_in_at)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.last_sign_in_at)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="删除" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LWMS/LWMS/Views/Shopper/Details.cshtml
@model LWMS.Models.users

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>users</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.login_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.login_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.photo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.photo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.created_user)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.created_user)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.created_at)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.created_at)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.updated_at)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.updated_at)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.encrypted_password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.encrypted_password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.remember_created_at)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.remember_created_at)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sign_in_count)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sign_in_count)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.current_sign_in_at)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.current_sign_in_at)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.last_sign_in_at)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.last_sign_in_at)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

LWMS/LWMS/Views/Shopper/Edit.cshtml
@model LWMS.Models.users

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>users</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">       
           <span class = "control-label col-md-2">登录名称</span> 
            <div class="col-md-10">
                @Html.EditorFor(model => model.login_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.login_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2">姓名</span>         
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2">照片 </span> 
  
            <div class="col-md-10">
                @Html.EditorFor(model => model.photo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.photo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2">创建人 </span> 
        
            <div class="col-md-10">
                @Html.EditorFor(model => model.created_user, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.created_user, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2"> 创建时间</span> 
        
            <div class="col-md-10">
                @Html.EditorFor(model => model.created_at, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.created_at, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2">更新时间 </span> 
        
            <div class="col-md-10">
                @Html.EditorFor(model => model.updated_at, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.updated_at, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2"> 加密密码</span> 
          
            <div class="col-md-10">
                @Html.EditorFor(model => model.encrypted_password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.encrypted_password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.remember_created_at, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.remember_created_at, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.remember_created_at, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sign_in_count, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sign_in_count, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sign_in_count, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.current_sign_in_at, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.current_sign_in_at, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.current_sign_in_at, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.last_sign_in_at, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.last_sign_in_at, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.last_sign_in_at, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

LWMS/LWMS/Views/Shopper/Index.cshtml
@model IEnumerable<LWMS.ViewModels.ShopperUser>

@{
    ViewBag.Title = "店长管理";
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>店长管理 </title>
    <script src="~/Scripts/jquery-1.10.2.js"></script>
</head>
<body>
    <h4>店长管理 </h4>
    <style type="text/css">
        .tr1 {
            background-color: #FF9933;
        }
    </style>
    <script language="JavaScript">
        $(function () {
            //$("#tb tr")--选择id为tb的table，再选择该table的行tr
            // mouseover--鼠标放上去的事件（悬停）
            //$("#tb tr").mouseover();--给tb的行tr添加鼠标悬停事件
            $("#tb tr").not("#tr1").mouseover(function () {
                $(this).addClass("tr1");//添加样式tr1，$(this)表示当前选择的元素。
            });
            // mouseout--鼠标离开的事件
            $("#tb tr").mouseout(function () {
                $(this).removeClass("tr1");//去掉样式tr1
            });

            $("#tb tr").not("#tr1").click(function () {
                var content = $(this).children("td:eq(0)").text(); //添加样式tr1，$(this)表示当前选择的元素。
                if (content!="") {
                    alert(content);
                }
            });
        });
    </script>

    @using (Html.BeginForm("action", "Shopper"))
    {
        <p>
            <input type="submit" value="添加店长" name="action:insert" class="btn btn-default" />

            <input type="submit" value="重置密码" name="action:setpassword" class="btn btn-default" />

        </p>

        <p>
            账号: @Html.TextBox("login_name")

            姓名: @Html.TextBox("name")

            角色: @Html.DropDownList("Roles", ViewBag.Roles as SelectList, "请选择")
            @*@Html.DropDownListFor(m => m.First().ListName, Model.First().GetSelectList(), "请选择")*@

            <input type="submit" value="搜索" name="action:search" class="btn btn-default" />
        </p>

    }
    <table class="table" id="tb">
        <tr id="tr1">
            <th></th>
            <th>            账号        </th>
            <th>            姓名        </th>
            <th>            创建时间        </th>
            <th>            创建人        </th>
            <th>            操作        </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td style="visibility:hidden;">
                    @Html.DisplayFor(modelItem => item.id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.login_name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.created_at)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.created_user)
                </td>
                <td>
                    @Html.ActionLink("编辑", "Edit", new { id = item.id }) |

                    @Html.ActionLink("删除", "Delete", new { id = item.id })
                </td>
            </tr>
        }

    </table>
</body>
</html>